from decouple import config, Csv

LOGI_NIT = config('LOGI_NIT')

# External Services from FevLogifarma
GOOGLE_TOKEN = config('GOOGLE_TOKEN')
GOOGLE_REFRESH_TOKEN = config('GOOGLE_REFRESH_TOKEN')
GOOGLE_TOKEN_URI = config('GOOGLE_TOKEN_URI')
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET')
GOOGLE_SCOPES = config('GOOGLE_SCOPES', cast=Csv())

LOGISTICA_GOOGLE_TOKEN = config('LOG_GOOGLE_TOKEN')
LOGISTICA_GOOGLE_REFRESH_TOKEN = config('LOG_GOOGLE_REFRESH_TOKEN')
LOGISTICA_GOOGLE_TOKEN_URI = config('GOOGLE_TOKEN_URI')
LOGISTICA_GOOGLE_CLIENT_ID = config('LOG_GOOGLE_CLIENT_ID')
LOGISTICA_GOOGLE_CLIENT_SECRET = config('LOG_GOOGLE_CLIENT_SECRET')
LOGISTICA_GOOGLE_SCOPES = config('LOG_GOOGLE_SCOPES', cast=Csv())

EMAILS_PER_EXECUTION = config('EMAILS_PER_EXECUTION', cast=int)

FACTURAS_TMP = "1dXonvccIt96nw6bVTLlnqzbXuBQirZAM"
FACTURAS_PDF = "1-ThpDhWgcxiqH5YxCGRSi9xes7llrDPe"
XMLS_CAJACOPI = "1LPLsobSVIAf3kWfeAbYbZPvew8kx0twO"
